---

# Currently supports:
#  - package
#  - binary
install_type: package

# Currently supports:
#  - mysql_community (WIP)
#  - percona (WIP)
mysql_flavor: mysql_community

# Comment out if using 'binary' install type
# mysql_repository: "deb http://dev.mysql.com/get/mysql-apt-config_0.3.3-1ubuntu12.04_all.deb precise partner"

# TODO: Convert to appropriate package based on version and flavor
# Optional: Minor version can be excluded, and play will download latest
mysql_version: 5.6

nofile_soft_limits: 64000
nofile_hard_limits: 64000

mysql_user: mysql
mysql_group: mysql

# TODO: Support upstart and systemd
mysql_init_file: /etc/init.d/mysql

# Ensure directory structure
mysql_dirs:
  - /var/log/mysql
  - "{{ mysql_conf['datadir'] }}"
  - "{{ mysql_conf['logdir'] }}"
  - "{{ mysql_conf['tmpdir'] }}"


# Used to configure templates/my.cnf.j2
mysql_conf:
  basedir: "/usr"
  datadir: "/var/lib/mysql"
  tmpdir: "/tmp/mysql"
  logdir: "/var/lib/mysql"
  socket: "/var/lib/mysql/mysql.sock"
  pidfile: "/var/lib/mysql/mysqld.pid"
  innodb:
    buffer_pool_size: "128M"

# TODO: define 'galera_options' for use in configuring templates/my.cnf.j2